import os
import sys

def resource_path(relative_path):
    """ Calcule le chemin absolu pour les ressources (indispensable pour le .exe) """
    if hasattr(sys, '_MEIPASS'):
        # Chemin vers le dossier temporaire du .exe
        return os.path.join(sys._MEIPASS, relative_path)
    # Chemin vers le dossier habituel en développement
    return os.path.join(os.path.abspath("."), relative_path)

# Fenêtre de jeu
WIDTH, HEIGHT = 1000, 500
COULEUR_FOND = (173,216,230)  # Bleu clair
FPS = 60

# Personnage
PERSONNAGE_DEPART_X = WIDTH/6
PERSONNAGE_DEPART_Y = HEIGHT * 2/3
PERSONNAGE_SKIN = resource_path("images/Man/Viking/viking_attaque_1.png")
PERSONNAGE_HEIGHT = 120

# Obstacles
OBSTACLE_DEPART_X = WIDTH + 50  # Spawn juste à la sortie de l'écran
OBSTACLE_DEPART_X_PREMIER = WIDTH * 2/3  # Position du premier obstacle (dans la fenêtre)
OBSTACLE_DEPART_Y = HEIGHT * 2/3
OBSTACLE_SKIN_DINO = resource_path("images/Mechant/dino")
OBSTACLE_NIMAGES_DINO = 4
OBSTACLE_NIMAGES_DINO_VOLANT = 7
OBSTACLE_VIMAGES_DINO_VOLANT = 7
OBSTACLE_SKIN_DINO_VOLANT = resource_path("images/Mechant/dino_volant")
OBSTACLE_TYPE = 2  # Méchant
OBSTACLE_HEIGHT = 120

# Mots
TAILLE_POLICE = 36
MOT_DEPART_X = WIDTH + 50  # Spawn juste à la sortie de l'écran
MOT_DEPART_X_PREMIER = WIDTH * 2/3  # Position du premier mot (dans la fenêtre)
MOT_DEPART_Y = HEIGHT * 2/3 - 50
MOT_COULEUR = (255, 255, 255)
MOT_SYMBOLE = 'début'  # Exemple de mot avec des caractères spéciaux
TOTAL_MOTS = 10

# Sol
SOL_DEPART_X = WIDTH / 2
SOL_DEPART_Y = HEIGHT
SOL_SKIN = resource_path("images/Sol/Terre.png")
SOL_VITESSE = 0.5
# Fond
FOND_SKIN = resource_path("images/Fond/volcan.jpg")
FOND_GAME_OVER = resource_path("images/Fond/volcan_erruption.jpg")

# Bandeau
BANDEAU_TEXTE = "Niveau "

# Niveaux
NB_NIVEAUX = 5
NIVEAU_BOUTON_TAILLE = 100
NIVEAU_BOUTON_ESPACEMENT = 30
NIVEAU_BOUTON_COULEUR_FOND = (200, 200, 200)
NIVEAU_BOUTON_COULEUR_BORDURE = (0, 0, 0)
NIVEAU_BOUTON_EPAISSEUR_BORDURE = 3
NIVEAU_TITRE_POLICE = 48

# Paramètres de jeu
VITESSE_POURCENTAGE_PAR_DEFAUT = 100  # Vitesse par défaut en pourcentage (100% = vitesse normale)
VITESSE_POURCENTAGE_MIN = 25  # 25% = vitesse lente
VITESSE_POURCENTAGE_MAX = 500  # 500% = 5x plus rapide
RESET_ON_ERROR_PAR_DEFAUT = True  # Si True, le mot est remis à zéro lors d'une erreur de frappe

# Couleurs interface
COULEUR_NOIR = (0, 0, 0)
COULEUR_BLANC = (255, 255, 255)
COULEUR_GRIS_FONCE = (50, 50, 50)
COULEUR_GRIS_MOYEN = (80, 80, 80)
COULEUR_GRIS_CLAIR = (100, 100, 100)
COULEUR_GRIS_TEXTE = (200, 200, 200)
COULEUR_VERT_FONCE = (0, 100, 0)
COULEUR_ROUGE_FONCE = (100, 0, 0)
COULEUR_BLEU_BOUTON = (100, 150, 200)

# Paramètres d'affichage de l'interface
BANDEAU_HAUTEUR = 40
BANDEAU_POLICE_TAILLE = 36
BANDEAU_ALPHA = 150
BANDEAU_MARGIN = 10

GAME_OVER_POLICE_TAILLE = 72
GAME_OVER_BANDEAU_HAUTEUR = 100
GAME_OVER_ALPHA = 150

STATS_FIN_ALPHA = 180
STATS_FIN_POLICE_TITRE = 60
STATS_FIN_POLICE_TEXTE = 40
STATS_FIN_TITRE_Y = 150
STATS_FIN_STATS_Y = 250
STATS_FIN_STATS_OFFSET_X = 150
STATS_FIN_LINE_HEIGHT = 50
STATS_FIN_MARGIN_BOTTOM = 60

PARAMS_POLICE_TITRE = 56
PARAMS_POLICE_VALEUR = 48
PARAMS_POLICE_INFO = 28
PARAMS_POLICE_PETITE = 22
PARAMS_TITRE_Y = 60
PARAMS_SOUS_TITRE_Y = 140
PARAMS_BOX_WIDTH = 200
PARAMS_BOX_HEIGHT = 70
PARAMS_BOX_BORDURE = 3
PARAMS_LABEL_OFFSET_X = 15
PARAMS_PLAGE_OFFSET_Y = 30
PARAMS_DERNIERE_OFFSET_Y = 55
PARAMS_RESET_OFFSET_Y = 80
PARAMS_RESET_STATUS_OFFSET_Y = 30
PARAMS_INFO_MARGIN_BOTTOM_1 = 110
PARAMS_INFO_MARGIN_BOTTOM_2 = 80
PARAMS_INFO_MARGIN_BOTTOM_3 = 50

NIVEAU_INFO_MARGIN = 30
NIVEAU_INFO_VITESSE_Y = 60
NIVEAU_INFO_RESET_Y = 90

NIVEAU_BOUTON_PARAMS_WIDTH = 150
NIVEAU_BOUTON_PARAMS_HEIGHT = 50
NIVEAU_BOUTON_PARAMS_MARGIN = 30
NIVEAU_BOUTON_PARAMS_BORDURE = 2
NIVEAU_TITRE_Y = 50
NIVEAU_POLICE_INFO = 32

# Paramètres menus joueur
MENU_JOUEUR_POLICE_ERREUR = 48
MENU_JOUEUR_POLICE_INFO = 36
MENU_JOUEUR_COULEUR_ERREUR = (255, 0, 0)
MENU_JOUEUR_ERREUR_OFFSET_X = 200
MENU_JOUEUR_ERREUR_OFFSET_Y = 30
MENU_JOUEUR_INFO_OFFSET_X = 180
MENU_JOUEUR_INFO_OFFSET_Y = 40

STATS_JOUEUR_POLICE_TITRE = 60
STATS_JOUEUR_POLICE_INFO = 40
STATS_JOUEUR_POLICE_LABEL = 32
STATS_JOUEUR_COULEUR_TITRE = (0, 100, 200)
STATS_JOUEUR_TITRE_Y = 30
STATS_JOUEUR_STATS_Y = 120
STATS_JOUEUR_LINE_HEIGHT = 50
STATS_JOUEUR_SECTION_SPACING = 20
STATS_JOUEUR_INFO_MARGIN_BOTTOM = 50

# Conversion WPM/Pourcentage
WPM_BASE_CONVERSION = 40.0
