import os
import sys
from BaseDonnees import Univers

def resource_path(relative_path):
    """ Calcule le chemin absolu pour les ressources (indispensable pour le .exe) """
    if hasattr(sys, '_MEIPASS'):
        # Chemin vers le dossier temporaire du .exe
        return os.path.join(sys._MEIPASS, relative_path)
    # Chemin vers le dossier habituel en développement
    return os.path.join(os.path.abspath("."), relative_path)

# Fenêtre de jeu
WIDTH, HEIGHT = 1000, 500
COULEUR_FOND = (173,216,230)  # Bleu clair
FPS = 60

# Personnage
PERSONNAGE_DEPART_X = WIDTH/6
PERSONNAGE_DEPART_Y = HEIGHT - 40  # Descendu de 10 pixels
# Note: Les personnages utilisent maintenant PERSONNAGES_CONFIG dans BaseDonnees.py
# PERSONNAGE_SKIN est conservé comme fallback pour la rétrocompatibilité
PERSONNAGE_SKIN = resource_path("images/Man/Viking/viking_attaque_1.png")
PERSONNAGE_HEIGHT = 120

# Obstacles
OBSTACLE_DEPART_X = WIDTH + 50  # Spawn juste à la sortie de l'écran
OBSTACLE_DEPART_X_PREMIER = WIDTH * 2/3  # Position du premier obstacle (dans la fenêtre)
OBSTACLE_DEPART_Y = HEIGHT - 40  # Descendu de 10 pixels
OBSTACLE_SKIN_DINO = resource_path("images/Mechant/dino")
OBSTACLE_NIMAGES_DINO = 4
OBSTACLE_NIMAGES_DINO_VOLANT = 7
OBSTACLE_VIMAGES_DINO_VOLANT = 7
OBSTACLE_SKIN_DINO_VOLANT = resource_path("images/Mechant/dino_volant")
OBSTACLE_TYPE = 2  # Méchant
OBSTACLE_HEIGHT = 120

# ⚙️ ALIGNEMENT DES PIEDS DES MÉCHANTS
# Offset vertical global pour aligner les pieds visuels des méchants avec ceux du personnage
# - Si les méchants sont TROP BAS : utilisez un offset NÉGATIF (ex: -10)
# - Si les méchants sont TROP HAUT : utilisez un offset POSITIF (ex: +10)
# - 0 = pas d'ajustement
MECHANT_FOOT_OFFSET = 17

# Mots
TAILLE_POLICE = 36
MOT_DEPART_X = WIDTH + 50  # Spawn juste à la sortie de l'écran
MOT_DEPART_X_PREMIER = WIDTH * 2/3  # Position du premier mot (dans la fenêtre)
MOT_DEPART_Y = HEIGHT - 180  # 140 pixels au-dessus du monstre
MOT_COULEUR = (255, 255, 255)
MOT_SYMBOLE = 'début'  # Exemple de mot avec des caractères spéciaux
TOTAL_MOTS = 3

# Sol
SOL_DEPART_X = WIDTH / 2
SOL_DEPART_Y = HEIGHT
SOL_SKIN = resource_path(Univers["foret_bleue"]["background"]["chemin"] + "1.png")
SOL_VITESSE = 0.5
# Fond avec parallaxe (6 couches, de la plus éloignée à la plus proche)
# L'image 7 est la plus éloignée (défille le moins vite)
# L'image 2 est la plus proche (défille presque aussi vite que le sol)
# L'image 1 est gérée par la classe Sol
FOND_SKIN = [resource_path(Univers["foret_bleue"]["background"]["chemin"] + f"{i}.png") for i in range(7, 1, -1)]
FOND_GAME_OVER = resource_path("images/Fond/volcan_erruption.jpg")

# Bandeau
BANDEAU_TEXTE = "Niveau "

# Niveaux
NB_NIVEAUX = 5
NIVEAU_BOUTON_TAILLE = 100
NIVEAU_BOUTON_ESPACEMENT = 30
NIVEAU_BOUTON_COULEUR_FOND = (200, 200, 200)
NIVEAU_BOUTON_COULEUR_BORDURE = (0, 0, 0)
NIVEAU_BOUTON_EPAISSEUR_BORDURE = 3
NIVEAU_TITRE_POLICE = 48

# Paramètres de jeu
VITESSE_POURCENTAGE_PAR_DEFAUT = 100  # Vitesse par défaut en pourcentage (100% = vitesse normale)
VITESSE_POURCENTAGE_MIN = 25  # 25% = vitesse lente
VITESSE_POURCENTAGE_MAX = 500  # 500% = 5x plus rapide
RESET_ON_ERROR_PAR_DEFAUT = True  # Si True, le mot est remis à zéro lors d'une erreur de frappe

# Couleurs interface
COULEUR_NOIR = (0, 0, 0)
COULEUR_BLANC = (255, 255, 255)
COULEUR_GRIS_FONCE = (50, 50, 50)
COULEUR_GRIS_MOYEN = (80, 80, 80)
COULEUR_GRIS_CLAIR = (100, 100, 100)
COULEUR_GRIS_TEXTE = (200, 200, 200)
COULEUR_VERT_FONCE = (0, 100, 0)
COULEUR_ROUGE_FONCE = (100, 0, 0)
COULEUR_BLEU_BOUTON = (100, 150, 200)

# Paramètres d'affichage de l'interface
BANDEAU_HAUTEUR = 40
BANDEAU_POLICE_TAILLE = 36
BANDEAU_ALPHA = 150
BANDEAU_MARGIN = 10

GAME_OVER_POLICE_TAILLE = 72
GAME_OVER_BANDEAU_HAUTEUR = 100
GAME_OVER_ALPHA = 150

STATS_FIN_ALPHA = 180
STATS_FIN_POLICE_TITRE = 60
STATS_FIN_POLICE_TEXTE = 40
STATS_FIN_TITRE_Y = 150
STATS_FIN_STATS_Y = 250
STATS_FIN_STATS_OFFSET_X = 150
STATS_FIN_LINE_HEIGHT = 50
STATS_FIN_MARGIN_BOTTOM = 60

# Fenêtre niveau réussi
NIVEAU_REUSSI_POLICE_TITRE = 80
NIVEAU_REUSSI_BANDEAU_ALPHA = 150
NIVEAU_REUSSI_BANDEAU_HAUTEUR = 120
NIVEAU_REUSSI_BOUTON_WIDTH = 250
NIVEAU_REUSSI_BOUTON_HEIGHT = 60
NIVEAU_REUSSI_BOUTON_Y = 350
NIVEAU_REUSSI_BOUTON_COULEUR = (100, 150, 200)
NIVEAU_REUSSI_BOUTON_POLICE = 36

# Fenêtre statistiques détaillées
STATS_DETAILS_ALPHA = 200
STATS_DETAILS_POLICE_TITRE = 56
STATS_DETAILS_POLICE_TEXTE = 32
STATS_DETAILS_POLICE_ERREUR = 28
STATS_DETAILS_TITRE_Y = 40
STATS_DETAILS_VITESSE_Y = 120
STATS_DETAILS_ERREUR_Y = 180
STATS_DETAILS_LIGNE_HEIGHT = 35
STATS_DETAILS_MARGIN_LEFT = 50
STATS_DETAILS_GRAPH_WIDTH = 250
STATS_DETAILS_GRAPH_HEIGHT = 300
STATS_DETAILS_GRAPH_X = 30
STATS_DETAILS_GRAPH_Y = 150
COULEUR_JAUNE = (255, 255, 0)
COULEUR_VERT = (0, 200, 0)

# Palette de couleurs pour les erreurs (couleurs vives et distinctes)
PALETTE_ERREURS = [
    (255, 100, 100),   # Rouge clair
    (100, 200, 255),   # Bleu clair
    (255, 200, 100),   # Orange clair
    (200, 100, 255),   # Violet clair
    (100, 255, 150),   # Vert clair
    (255, 150, 200),   # Rose
    (150, 255, 255),   # Cyan clair
    (255, 255, 100),   # Jaune clair
    (255, 150, 100),   # Corail
    (150, 200, 255),   # Bleu pervenche
]

PARAMS_POLICE_TITRE = 56
PARAMS_POLICE_VALEUR = 48
PARAMS_POLICE_INFO = 28
PARAMS_POLICE_PETITE = 22
PARAMS_TITRE_Y = 60
PARAMS_SOUS_TITRE_Y = 140
PARAMS_BOX_WIDTH = 200
PARAMS_BOX_HEIGHT = 70
PARAMS_BOX_BORDURE = 3
PARAMS_LABEL_OFFSET_X = 15
PARAMS_PLAGE_OFFSET_Y = 30
PARAMS_DERNIERE_OFFSET_Y = 55
PARAMS_RESET_OFFSET_Y = 80
PARAMS_RESET_STATUS_OFFSET_Y = 30
PARAMS_INFO_MARGIN_BOTTOM_1 = 110
PARAMS_INFO_MARGIN_BOTTOM_2 = 80
PARAMS_INFO_MARGIN_BOTTOM_3 = 50

NIVEAU_INFO_MARGIN = 30
NIVEAU_INFO_VITESSE_Y = 60
NIVEAU_INFO_RESET_Y = 90

NIVEAU_BOUTON_PARAMS_WIDTH = 150
NIVEAU_BOUTON_PARAMS_HEIGHT = 50
NIVEAU_BOUTON_PARAMS_MARGIN = 30
NIVEAU_BOUTON_PARAMS_BORDURE = 2
NIVEAU_TITRE_Y = 50
NIVEAU_POLICE_INFO = 32

# Paramètres menus joueur
MENU_JOUEUR_POLICE_ERREUR = 48
MENU_JOUEUR_POLICE_INFO = 36
MENU_JOUEUR_COULEUR_ERREUR = (255, 0, 0)
MENU_JOUEUR_ERREUR_OFFSET_X = 200
MENU_JOUEUR_ERREUR_OFFSET_Y = 30
MENU_JOUEUR_INFO_OFFSET_X = 180
MENU_JOUEUR_INFO_OFFSET_Y = 40

STATS_JOUEUR_POLICE_TITRE = 60
STATS_JOUEUR_POLICE_INFO = 40
STATS_JOUEUR_POLICE_LABEL = 32
STATS_JOUEUR_COULEUR_TITRE = (0, 100, 200)
STATS_JOUEUR_TITRE_Y = 30
STATS_JOUEUR_STATS_Y = 120
STATS_JOUEUR_LINE_HEIGHT = 50
STATS_JOUEUR_SECTION_SPACING = 20
STATS_JOUEUR_INFO_MARGIN_BOTTOM = 50

# Fenêtre paramètres - Zones
PARAMS_ZONE_TITRE_RATIO = 6  # HEIGHT // PARAMS_ZONE_TITRE_RATIO
PARAMS_ZONE_PARAMS_RATIO = 2  # HEIGHT // PARAMS_ZONE_PARAMS_RATIO
PARAMS_PARAM_HEIGHT = 50
PARAMS_LABEL_X_RATIO = 4  # WIDTH // PARAMS_LABEL_X_RATIO
PARAMS_INPUT_X_OFFSET = 50  # WIDTH // 2 + PARAMS_INPUT_X_OFFSET

# Fenêtre paramètres - Input box
PARAMS_INPUT_BOX_WIDTH = 250
PARAMS_INPUT_BOX_HEIGHT = 50
PARAMS_INPUT_BOX_BORDURE = 3
PARAMS_INPUT_BOX_COULEUR_ACTIVE = (100, 150, 255)

# Fenêtre paramètres - Checkbox
PARAMS_CHECKBOX_SIZE = 40
PARAMS_CHECKBOX_OFFSET_X = 50  # Offset par rapport à input_x
PARAMS_CHECKBOX_OFFSET_Y = 5
PARAMS_CHECKMARK_MARGIN_LEFT = 8
PARAMS_CHECKMARK_MARGIN_TOP = 8
PARAMS_CHECKMARK_MARGIN_RIGHT = 3
PARAMS_CHECKMARK_MARGIN_BOTTOM = 10
PARAMS_CHECKMARK_EPAISSEUR = 5

# Fenêtre paramètres - Boutons
PARAMS_BOUTON_WIDTH = 180
PARAMS_BOUTON_HEIGHT = 50
PARAMS_BOUTON_SPACING = 40
PARAMS_BOUTON_COULEUR_VALIDER = (100, 200, 100)
PARAMS_BOUTON_COULEUR_RETOUR = (220, 100, 100)

# Fenêtre paramètres - Polices
PARAMS_FENETRE_POLICE_TITRE = 64
PARAMS_FENETRE_POLICE_LABEL = 36
PARAMS_FENETRE_POLICE_INPUT = 42
PARAMS_FENETRE_POLICE_BOUTON = 40

# Fenêtre paramètres - Séparations
PARAMS_LIGNE_SEPARATION_COULEUR = (200, 200, 200)
PARAMS_LIGNE_SEPARATION_EPAISSEUR = 2
PARAMS_LIGNE_SEPARATION_OFFSET = 10
PARAMS_LIGNE_SEPARATION_RATIO = 6  # WIDTH // PARAMS_LIGNE_SEPARATION_RATIO

# Conversion WPM/Pourcentage
WPM_BASE_CONVERSION = 40.0
